name: proxy-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/**'

jobs:
  build:
    name: "Deploy To Dev"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate
        run: echo "Authentication step"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Build Docker Image
        run: docker build -t your-docker-image-name .

      - name: Tag Docker Image
        run: docker tag your-docker-image-name gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image-name:latest

      - name: Authenticate to Google Cloud
        run: gcloud auth configure-docker

      - name: Push Docker Image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image-name:latest

      - name: Deploy Apigee Proxy
        run: |
          # Add commands to deploy Apigee proxy here
          # Example: apigeetool deployproxy ...

